Projeto-1/DriveClone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("mainapp.urls")),
    path("accounts/", include("accounts.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projeto-1/mainapp/urls.py
from django.urls import path
from . import views
from .views_api import ProfileStorageView



app_name = "mainapp"

urlpatterns = [
    path("", views.home, name="home"),
    path("create-folder", views.create_new_folder, name="create_new_folder"),
    path("folder/<str:pk>", views.open_folder, name="open_folder"),
    path("upload-new-file/", views.upload_file,  name="upload_file"),
    path("delete_file/", views.delete_file, name="delete_file"),
    path("delete_folder/<str:pk>", views.delete_folder, name="delete_folder"),
    path("download/<str:pk>", views.download, name="download"),
    path('api/storage-usage/', ProfileStorageView.as_view(), name='storage_usage')
]

Projeto-1/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
import shutil


# Create your models here.
def get_file_location(instance, filename):
    current_location = instance.folder
    path = ""
    while current_location:
        path = f"/{current_location.name}" + path
        current_location = current_location.folder

    return f"files/{instance.folder.user.username}{path}/{filename}"



def get_folder_location(current_folder):
    username = current_folder.user.username
    path = ""
    while current_folder:
        path = f"/{current_folder.name}" + path
        current_folder = current_folder.folder
    return f"media/files/{username}{path}"


class Folder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="folders")
    name = models.CharField(max_length=200)
    folder = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, related_name="folders_within"
    )

    def __str__(self):
        return f"{self.user} - {self.name}"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["folder", "name"], name="unique_folder_name"
            ),
            models.UniqueConstraint(
                fields=["user", "name"],
                condition=Q(folder=None),
                name="unique_user_folder",
            ),
        ]

    def delete(self, *args, **kwargs):
        shutil.rmtree(get_folder_location(self))
        super().delete(*args, **kwargs)


class File(models.Model):
    folder = models.ForeignKey(
        Folder, on_delete=models.CASCADE, null=True, related_name="allfiles"
    )
    files = models.FileField(upload_to=get_file_location)
    filename = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return f"{self.files}"

    def save(self, *args, **kwargs):
        if not self.pk:  
            self.filename = self.files.name
            self.folder.user.profile.used_storage += self.files.size
            self.folder.user.profile.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        file_size = self.files.size
        super().delete(*args, **kwargs)  
        self.folder.user.profile.used_storage -= file_size
        self.folder.user.profile.save()

Projeto-1/mainapp/forms.py
from django import forms
from .models import Folder


class NewFolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ("name",)

Projeto-1/mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import NewFolderForm
from .models import Folder, File, get_folder_location
from django.contrib import messages
from django.db import IntegrityError
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from http import HTTPStatus
from django.http import FileResponse
import json
import os
from .decorators import admin_forbiden

@admin_forbiden
@login_required
def home(request):
    folders = request.user.folders.filter(folder=None)
    return render(request, "home.html", {"folders": folders})

@admin_forbiden
@login_required
def create_new_folder(request):
    if request.method == "POST":
        if request.session["redirected_from"] is None:
            messages.error(
                request,
                "Folder not created!  You are not allowed to access this page directly.",
            )
            return HttpResponseRedirect("/")
        form = NewFolderForm(request.POST)

        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user  # Currently logged in user
            redirected_from = request.session["redirected_from"].split("/")
            if redirected_from[3] != "":  # Creating folder in a folder
                pk = redirected_from[-1]
                form.folder = get_object_or_404(Folder, pk=pk)
            try:
                form.save()
                path = get_folder_location(form)
                os.makedirs(path, exist_ok=True)
            except IntegrityError:
                messages.error(request, "Folder with this name already exists!")
            return HttpResponseRedirect(request.session["redirected_from"])
    else:
        request.session["redirected_from"] = request.META.get("HTTP_REFERER")
        createfolder = NewFolderForm()
    return render(request, "create_new_folder.html", {"createfolder": createfolder})

@admin_forbiden
@login_required
def open_folder(request, pk):
    try:
        folder = get_object_or_404(Folder, pk=pk)
    except:
        messages.error(request, "Folder not found!")
        return HttpResponseRedirect("/")
    return render(request, "openFolder.html", {"folder": folder})

@admin_forbiden
@login_required
def upload_file(request):

    uploaded_file = request.FILES.get("uploadfile")
    folder_id = request.POST.get("fid")
    folder = get_object_or_404(Folder, pk=folder_id)
    try:
        File.objects.create(folder=folder, files=uploaded_file)
    except:
        messages.error(request, "Please chose a file")
    return redirect("mainapp:open_folder", pk=folder_id)


@admin_forbiden
@login_required
def delete_file(request):
    if request.method == "POST":
        data = json.loads(request.body)
        pk = data.get("pk")
        user = data.get("user")

        if request.user.username != user:
            return JsonResponse({"error": "Unauthorized user", "status": HTTPStatus.UNAUTHORIZED})

        delfile = get_object_or_404(File, pk=pk)
        delfile.delete()

        return JsonResponse({delfile.filename: "Deleted", "status": HTTPStatus.OK})

    return JsonResponse(
        {"error": "Invalid request method", "status": HTTPStatus.METHOD_NOT_ALLOWED})


@admin_forbiden
@login_required
def delete_folder(request, pk):
    folder = get_object_or_404(Folder, pk=pk)
    try:
        fid = folder.folder.pk
    except:
        return redirect("mainapp:home")
    else:
        return redirect("mainapp:open_folder", pk=fid)
    finally:
        folder.delete()


@admin_forbiden
@login_required
def download(request, pk):
    file_instance = get_object_or_404(File, pk=pk)
    file_path = file_instance.files.path
    return FileResponse(open(file_path, 'rb'), as_attachment=True, filename=file_instance.files.name)

Projeto-1/mainapp/templates/create_new_folder.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static "css/create-folder.css" %}">
    {% if messages %}
    {% for message in messages  %}
        {{message}} <br>
    {% endfor %}
    {% endif %}
    <h2>Create New Folder</h2>
    <form method="post">
        {% csrf_token %}
        {{ createfolder.as_p }}
        <button type="submit">Create</button>
    </form>

{% endblock content %}

Projeto-1/mainapp/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <br>
    <h2>CloudSync</h2>
    <img src="{% static 'media/hero.webp' %}" alt="Home" width="400" height="400" />   
    <br>
    <p>Welcome to the home page.</p>
    <p>Click on the buttons below to navigate to the respective repositorys.</p>
    <ul>
        <li><a href="{% url 'mainapp:create_new_folder' %}"><button>Create New Folder </button> </a></li>
    </ul>
    <br>
    {% for folder in folders  %}
        <ul>
            <li><a href="{% url "mainapp:open_folder" folder.pk %}"><button id="folder-btn">{{ folder.name|linebreaks }}</button></a></li>
        </ul>
    {% endfor %}
{% endblock content %}

Projeto-1/mainapp/templates/openFolder.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% include "upload_file.html" %}
{% include "storage_bar.html" %}
<link rel="stylesheet" type="text/css" href="{% static 'css/open-folder.css' %}">
    <h2>CloudSync</h2>
    <img id="open-folder-image" src="{% static "media/hero.webp" %}">
    <h3>Folder Name: {{folder.name}}</h3>
    <div id="new-folder">
        <a href={% url "mainapp:create_new_folder" %}><button>New folder</button></a>
    </div>
    {% comment %} Delete folder {% endcomment %}

    <form action="{% url "mainapp:delete_folder" folder.pk %}" method="post">
        {% csrf_token %}
        <button type="submit">Delete Folder</button>
    </form>
    {% comment %} Folder {% endcomment %}

    <h3>Folders and files inside {{folder.name}} folder</h4>
    {% for folder in folder.folders_within.all  %}
        <div id="folder-within">
           <br> <a href="{% url "mainapp:open_folder" folder.pk %}"><button id="folder-btn">{{ folder.name|linebreaks }} </button></a>
        </div>
    {% endfor %}

    {% comment %} Files/Delete File {% endcomment %}

    {% for file in folder.allfiles.all  %}
        <div id="file">
            <a href="{{file.files.url}}">{{file.filename}} </a> - <button onclick="delfile(this.id)" class="button" id="{{file.pk}}">Delete</button> - <a href="{% url "mainapp:download" file.pk %}">Download</a>  <br>
        </div>
    {% endfor %}

    <div id="back">
        <a href="{% url "mainapp:home" %}"><button>Back</button></a>
    </div>

    <div id="context-menu" class="context-menu">
        <ul>
            <a href={% url "mainapp:create_new_folder" %}><li onclick="createFolder()">Create Folder</li></a>
        </ul>
    </div>

{% endblock content %}

{% block script %}

    <script>

        document.addEventListener('DOMContentLoaded', function() {
            const contextMenu = document.getElementById('context-menu');
            let currentFolderId = {{ folder.pk }};
    
            document.addEventListener('contextmenu', function(e) {
                e.preventDefault();
                contextMenu.style.top = `${e.clientY}px`;
                contextMenu.style.left = `${e.clientX}px`;
                contextMenu.style.display = 'block';
            });
    
            document.addEventListener('click', function() {
                contextMenu.style.display = 'none';
            });
    
            window.createFolder = function() {
                const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                fetch("{% url 'mainapp:create_new_folder' %}", {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': csrftoken,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ parent_id: currentFolderId })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'success') {
                        window.location.reload();
                    }
                })
                .catch(error => console.error('Error:', error));
            };
        });
        
        const delfile = (del_file_id) => {
            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            fetch("{% url 'mainapp:delete_file' %}", {
                method: "POST",
                headers: {
                    "X-CSRFToken": csrftoken,
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    pk: del_file_id,
                    user: "{{ request.user.username }}"
                })
            })
            .then(response => response.json())
            .then(data => {
                console.log(data);
                if (data.status === 200) {
                    document.getElementById(del_file_id).parentElement.remove();
                    updateStorageBar();
                }
            })
            .catch(error => console.error('Error:', error));
        };
    
    </script>
    


{% endblock script %}

Projeto-1/mainapp/templates/storage_bar.html
<style>
    .storage-bar-container {
        position: absolute;
        width: 20%;
        background-color: #f3f3f3;
        border-radius: 25px;
        overflow: hidden;
        height: 30px;
        margin: 30px 0;
    }

    .storage-bar {
        height: 100%;
        width: 0;
        background-color: #4caf50;
        text-align: center;
        line-height: 30px; /* same as container height */
        color: black;
        border-radius: 25px;
    }
</style>
<h3>Storage Usage</h3>
<div class="storage-bar-container">
    <div class="storage-bar" id="storageBar">0%</div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        fetch('/api/storage-usage/', {
            headers: {
                'Authorization': 'Bearer ' + localStorage.getItem('token')
            }
        })
        .then(response => response.json())
        .then(data => {
            var usedStorage = data.used_storage;
            var allowedStorage = data.allowed_storage;
            var usedStoragePercentage = (usedStorage / allowedStorage) * 100;

            var storageBar = document.getElementById('storageBar');
            storageBar.style.width = usedStoragePercentage + '%';
            storageBar.innerText = usedStoragePercentage.toFixed(2) + '%';
        })
        .catch(error => console.error('Error fetching storage usage data:', error));
    });
</script>

Projeto-1/mainapp/templates/upload_file.html
<form id="upload-file" method="post" enctype="multipart/form-data" action="{% url "mainapp:upload_file" %}">
    {% csrf_token %}
    <div class="modal-body">
        <input type="file" id="myFile" name="uploadfile" >
        <input type="hidden" name="fid" value="{{folder.pk}}">
    </div>
    <div class="modal-footer">
        <button type="submit" id="file-button" class="btn btn-primary">Upload</button>
    </div>
</form>

<script>

    let file = document.getElementById('myFile');
    file.addEventListener("change", function(){
        let remaining_storage = parseInt("{{request.user.profile.allowed_storage}}") - parseInt("{{request.user.profile.used_storage}}");
        let remaining_storage_mb = (remaining_storage / 1024) / 1024;
        console.log(file.files[0].size, remaining_storage_mb);
        if (file.files[0].size>remaining_storage){
            alert("You don't have enough storage to upload this file. You have "+remaining_storage_mb.toFixed(2)+" MB remaining.");
            document.getElementById('file-button').disabled = true;
        }
        else{
            alert("File acepted, You have enough storage to upload this file. " +remaining_storage_mb.toFixed(2)+" MB remaining.");
            document.getElementById('file-button').disabled = false;
        }
    })
    
    document.getElementById('file-button').addEventListener("click", function() {
        if (file.files.length === 0) {
            alert("Please choose a file to upload.");
        }
    });

</script>
                