Projeto-1/DriveClone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("mainapp.urls")),
    path("accounts/", include("accounts.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projeto-1/accounts/urls.py
from django.urls import path
from .views import user_login, logout_user, register, profile
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name='logged_out.html'), name="logout"),
    path("register/", register, name="register"),
    path("profile/", profile, name="profile")
]

Projeto-1/mainapp/urls.py
from django.urls import path
from . import views
from .views_api import ProfileStorageView



app_name = "mainapp"

urlpatterns = [
    path("", views.home, name="home"),
    path("create-folder", views.create_new_folder, name="create_new_folder"),
    path("folder/<str:pk>", views.open_folder, name="open_folder"),
    path("upload-new-file/", views.upload_file,  name="upload_file"),
    path("delete_file/", views.delete_file, name="delete_file"),
    path("delete_folder/<str:pk>", views.delete_folder, name="delete_folder"),
    path("download/<str:pk>", views.download, name="download"),
    path('api/storage-usage/', ProfileStorageView.as_view(), name='storage_usage')
]

Projeto-1/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CloudSync</title>
    {% load static %}
    <link rel="icon" href="{% static 'media/logo-transformed.webp' %}">
  </head>
  <body>
    {% block content %}{% endblock content %}
    
    {% if request.user.is_authenticated %}
    <a id="change-profile" href="{% url 'accounts:profile' %}">Your Profile - {{request.user}}</a>
    <img id="icon-user" src="{% static 'media/icon-user.webp' %}" alt="User" width="75" height="75" />
    
    <form method="post" action="{% url 'logout' %}"> 
      {% csrf_token %} 
      <button id="logout-button" type="submit">Logout</button>
    </form>
    {% endif %}
    {% if messages %}
      {% for message in messages  %}
        <p>{{ message }}</p>
      {% endfor %}
    {% endif %}
    
  </body>
  {% block script %}{% endblock script %}
</html>